[package]
authors = ["Matěj Volf"]
edition = '2021'
license = "MIT"
name = "blikato"
version = "0.1.0"

[dependencies]
ruduino = {git = "https://github.com/avr-rust/ruduino", branch = "master"}

[profile.release]
lto = true
